[Interface]
PrivateKey = <Raspberry-private-key>
Address = 10.10.0.2/24

# Allow traffic between peers
PostUp = iptables -I FORWARD 1 -i wg0 -o wg0 -j ACCEPT

# Tabela NAT para acessar a LAN
PostUp = iptables -t nat -A POSTROUTING -o YOUR_NETWORK_INTERFACE -j MASQUERADE # Type your LAN interface here. Ex.: eth0 or wlan0

# Clean up rules
PostDown = iptables -D FORWARD -i wg0 -o wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o YOUR_NETWORK_INTERFACE -j MASQUERADE # Type your LAN interface here. Ex.: eth0 or wlan0

# VPS
[Peer]
PublicKey = <VPS-public-key>
Endpoint = VPS_PUBLIC_IP:51820
AllowedIPs = 10.10.0.0/24

# Keep connection for CGNAT workaround
PersistentKeepalive = 25
