[Interface]
PrivateKey = <VPS-private-key>
Address = 10.10.0.1/24
ListenPort = 51820

# Allow traffic between peers
PostUp = iptables -I FORWARD 1 -i wg0 -o wg0 -j ACCEPT

# Clean up rules
PostDown = iptables -D FORWARD -i wg0 -o wg0 -j ACCEPT

# Raspberry
[Peer]
PublicKey = <Raspberry-public-key>
AllowedIPs = 10.10.0.2/32, 192.168.0.0/24 # Your LAN IP mask

# Client
[Peer]
PublicKey = <Client-public-key>
AllowedIPs = 10.10.0.3/32
